version: "3.4"
services:
 vite_docker:
   build:
      context: ./  
      dockerfile: Dockerfile  
      args:
        - NODE_VERSION=18 
   image: glennin/mobile-wallet-frontend:latest
   container_name: front-mobile-walllet
   entrypoint: /bin/sh
   ports:
     - 8000:8000
   working_dir: /srv/app
   volumes:
     - type: bind
       source: ./
       target: /srv/app
   tty: true
